package com.github.kotatsu_rtm.kotatsulib.api.enum.gl

import org.lwjgl.opengl.GL43

@Suppress("unused")
enum class DebugSource(val constant: Int) {
    GL_DEBUG_SOURCE_API(GL43.GL_DEBUG_SOURCE_API),
    GL_DEBUG_SOURCE_WINDOW_SYSTEM(GL43.GL_DEBUG_SOURCE_WINDOW_SYSTEM),
    GL_DEBUG_SOURCE_SHADER_COMPILER(GL43.GL_DEBUG_SOURCE_SHADER_COMPILER),
    GL_DEBUG_SOURCE_THIRD_PARTY(GL43.GL_DEBUG_SOURCE_THIRD_PARTY),
    GL_DEBUG_SOURCE_APPLICATION(GL43.GL_DEBUG_SOURCE_APPLICATION),
    GL_DEBUG_SOURCE_OTHER(GL43.GL_DEBUG_SOURCE_OTHER)
}
