name: Build

on: [push, workflow-dispatch]

jobs:
  build:
    name: Build
    uses: Kotatsu-RTM/.github/.github/workflows/rtmpack_build.yml@master

  publish:
    name: Publish artifacts to the Maven repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Setup JDK8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: gradle

      # We're already validated gradle wrapper at build, so skip validation.
      - name: Add permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Publish
        env:
          NexusUsername: ${{ secrets.SIRO256_NEXUS_USER }}
          NexusPassword: ${{ secrets.SIRO256_NEXUS_PASSWORD }}
          SigningKeyId: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY_ID }}
          SigningKey: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY }}
          SigningKeyPassword: ${{ secrets.SIRO256_MAVEN_SIGNING_KEY_PASSWORD }}
        run: ./gradlew publish
